import { PartState } from "./part_state";
import { unit } from "mathjs";

interface MouserPartResponse {
  MouserPartNumber: string;
  ManufacturerPartNumber: string;
  Manufacturer: string;
  Description: string;
  ProductDetailUrl: string;
  DataSheetUrl: string;
  Availability: string;
  PriceBreaks: { Quantity: number; Price: string }[];
  ProductAttributes: { AttributeName: string; AttributeValue: string }[];
  SearchResults: { NumberOfResult: number; Parts: any[] };
}

export async function searchMouser(partNumber: string): Promise<PartState | null> {
  const apiKey = process.env.MOUSER_API_KEY;

  if (!apiKey) {
    throw new Error("MOUSER_API_KEY environment variable is not set");
  }

  const response = await fetch(
    `https://api.mouser.com/api/v1/search/partnumber?apiKey=${apiKey}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        SearchByPartRequest: {
          mouserPartNumber: partNumber,
          partSearchOptions: "Exact",
        },
      }),
    }
  );

  if (!response.ok) {
    throw new Error(`Mouser API error: ${response.statusText}`);
  }

  const data = await response.json();
  const parts = data.SearchResults?.Parts;

  if (!parts || parts.length === 0) {
    return null;
  }

  // Take the first result
  const result = parts[0];
  return mapMouserResponseToPartState(result);
}

// Helper to convert to specific units if possible, otherwise base
function parseValue(value: string, targetUnit?: string): number | undefined {
    if (!value) return undefined;
    try {
        const u = unit(value);
        if (targetUnit) {
            return u.toNumber(targetUnit);
        }
        return u.toNumber(); // Base unit
    } catch (e) {
        const num = parseFloat(value);
        return isNaN(num) ? undefined : num;
    }
}

function mapMouserResponseToPartState(result: any): PartState {
  const attributes = result.ProductAttributes || [];
  const getAttr = (name: string) =>
    attributes.find((a: any) => a.AttributeName === name)?.AttributeValue;

  return {
    id: 0, // Placeholder, generated by DB
    title: result.Description,
    quantity: result.Availability ? parseInt(result.Availability.replace(/[^0-9]/g, "")) : 0,
    productId: 0, // Mouser does not provide a numeric ProductId that maps to our schema.
    productCode: result.MouserPartNumber,
    productModel: result.ManufacturerPartNumber,
    productDescription: result.Description,
    catalogName: "Electronic Components",
    brandName: result.Manufacturer,
    productImages: result.ImagePath ? [result.ImagePath] : [],
    pdfLink: result.DataSheetUrl,
    productLink: result.ProductDetailUrl,
    createdAt: new Date(),
    updatedAt: new Date(),
    
    // Parse technical parameters
    voltage: parseValue(getAttr("Voltage Rating"), "V"),
    resistance: parseValue(getAttr("Resistance"), "ohm"),
    power: parseValue(getAttr("Power Rating"), "W"),
    current: parseValue(getAttr("Current Rating"), "A"),
    tolerance: getAttr("Tolerance"), 
    frequency: parseValue(getAttr("Frequency"), "Hz"),
    capacitance: parseValue(getAttr("Capacitance"), "nF"),
    inductance: parseValue(getAttr("Inductance"), "uH"),
    
    prices: result.PriceBreaks?.map((pb: any) => ({
      ladder: pb.Quantity.toString(),
      price: parseFloat(pb.Price.replace(',', '.').replace(/[^0-9.]/g, "")),
    })),
  };
}
